# Generated by Django 5.0.6 on 2024-07-15 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_record_province_record_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Agent',
        ),
    ]
