# Generated by Django 5.0.6 on 2024-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_record_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Staff Member', 'Staff Member')], max_length=200, null=True),
        ),
    ]
