# Generated by Django 5.0.6 on 2024-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_agent_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Assistant Manager', 'Assistant Manager'), ('Staff Member', 'Staff Member'), ('Tester', 'Tester')], max_length=200, null=True),
        ),
    ]
